/*
  Warnings:

  - You are about to drop the `Salon` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `User` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Salon";

-- DropTable
DROP TABLE "User";

-- CreateTable
CREATE TABLE "ROLES" (
    "Role_ID" SERIAL NOT NULL,
    "Role_Name" TEXT NOT NULL,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("Role_ID")
);

-- CreateTable
CREATE TABLE "USERS" (
    "User_ID" SERIAL NOT NULL,
    "Role_ID" INTEGER,
    "Full_Name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "Phone" TEXT,
    "Password_Hash" TEXT NOT NULL,
    "Loyalty_Points" INTEGER NOT NULL DEFAULT 0,
    "Refresh_Token" TEXT,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("User_ID")
);

-- CreateTable
CREATE TABLE "EMPLOYEE_SKILLS" (
    "Skill_ID" SERIAL NOT NULL,
    "Employee_ID" INTEGER NOT NULL,
    "Service_ID" INTEGER NOT NULL,

    CONSTRAINT "EMPLOYEE_SKILLS_pkey" PRIMARY KEY ("Skill_ID")
);

-- CreateTable
CREATE TABLE "EMPLOYEE_SCHEDULES" (
    "Schedule_ID" SERIAL NOT NULL,
    "Employee_ID" INTEGER NOT NULL,
    "Work_Date" DATE NOT NULL,
    "Start_Time" TIME NOT NULL,
    "End_Time" TIME NOT NULL,
    "Status" TEXT NOT NULL,

    CONSTRAINT "EMPLOYEE_SCHEDULES_pkey" PRIMARY KEY ("Schedule_ID")
);

-- CreateTable
CREATE TABLE "SERVICES" (
    "Service_ID" SERIAL NOT NULL,
    "Service_Name" TEXT NOT NULL,
    "Duration_Min" INTEGER NOT NULL,
    "Price" DECIMAL(65,30) NOT NULL,
    "Commission_Rate" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "SERVICES_pkey" PRIMARY KEY ("Service_ID")
);

-- CreateTable
CREATE TABLE "PACKAGES" (
    "Package_ID" SERIAL NOT NULL,
    "Package_Name" TEXT NOT NULL,
    "Total_Sessions" INTEGER NOT NULL,
    "Price" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "PACKAGES_pkey" PRIMARY KEY ("Package_ID")
);

-- CreateTable
CREATE TABLE "CUSTOMER_PACKAGES" (
    "Cust_Pkg_ID" SERIAL NOT NULL,
    "Customer_ID" INTEGER NOT NULL,
    "Package_ID" INTEGER NOT NULL,
    "Remaining_Sessions" INTEGER NOT NULL,

    CONSTRAINT "CUSTOMER_PACKAGES_pkey" PRIMARY KEY ("Cust_Pkg_ID")
);

-- CreateTable
CREATE TABLE "INVOICES" (
    "Invoice_ID" SERIAL NOT NULL,
    "Customer_ID" INTEGER NOT NULL,
    "Total_Amount" DECIMAL(65,30) NOT NULL,
    "Payment_Method" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    "Created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "INVOICES_pkey" PRIMARY KEY ("Invoice_ID")
);

-- CreateTable
CREATE TABLE "BOOKINGS" (
    "Booking_ID" SERIAL NOT NULL,
    "Customer_ID" INTEGER NOT NULL,
    "Invoice_ID" INTEGER NOT NULL,
    "Arrival_Time" TIMESTAMP(3) NOT NULL,
    "Status" TEXT NOT NULL,

    CONSTRAINT "BOOKINGS_pkey" PRIMARY KEY ("Booking_ID")
);

-- CreateTable
CREATE TABLE "BOOKING_DETAILS" (
    "Booking_Detail_ID" SERIAL NOT NULL,
    "Booking_ID" INTEGER NOT NULL,
    "Service_ID" INTEGER NOT NULL,
    "Cust_Pkg_ID" INTEGER,
    "Start_Time" TIMESTAMP(3) NOT NULL,
    "End_Time" TIMESTAMP(3) NOT NULL,
    "Actual_Price" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "BOOKING_DETAILS_pkey" PRIMARY KEY ("Booking_Detail_ID")
);

-- CreateTable
CREATE TABLE "BOOKING_EMPLOYEES" (
    "BE_ID" SERIAL NOT NULL,
    "Booking_Detail_ID" INTEGER NOT NULL,
    "Employee_ID" INTEGER NOT NULL,
    "Role_Type" TEXT NOT NULL,
    "Commission_Earned" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "BOOKING_EMPLOYEES_pkey" PRIMARY KEY ("BE_ID")
);

-- CreateTable
CREATE TABLE "CUSTOMER_PROGRESS" (
    "Progress_ID" SERIAL NOT NULL,
    "Booking_Detail_ID" INTEGER NOT NULL,
    "Img_Before_Url" TEXT,
    "Img_After_Url" TEXT,
    "Notes" TEXT,

    CONSTRAINT "CUSTOMER_PROGRESS_pkey" PRIMARY KEY ("Progress_ID")
);

-- CreateTable
CREATE TABLE "PRODUCTS" (
    "Product_ID" SERIAL NOT NULL,
    "Product_Name" TEXT NOT NULL,
    "Price" DECIMAL(65,30) NOT NULL,
    "Stock_Quantity" INTEGER NOT NULL,
    "Commission_Rate" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "PRODUCTS_pkey" PRIMARY KEY ("Product_ID")
);

-- CreateTable
CREATE TABLE "ORDERS" (
    "Order_ID" SERIAL NOT NULL,
    "Customer_ID" INTEGER NOT NULL,
    "Invoice_ID" INTEGER NOT NULL,
    "Status" TEXT NOT NULL,

    CONSTRAINT "ORDERS_pkey" PRIMARY KEY ("Order_ID")
);

-- CreateTable
CREATE TABLE "ORDER_DETAILS" (
    "Order_Detail_ID" SERIAL NOT NULL,
    "Order_ID" INTEGER NOT NULL,
    "Product_ID" INTEGER NOT NULL,
    "Employee_ID" INTEGER NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "Unit_Price" DECIMAL(65,30) NOT NULL,
    "Commission_Earned" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "ORDER_DETAILS_pkey" PRIMARY KEY ("Order_Detail_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_email_key" ON "USERS"("email");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_Phone_key" ON "USERS"("Phone");

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_Role_ID_fkey" FOREIGN KEY ("Role_ID") REFERENCES "ROLES"("Role_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_SKILLS" ADD CONSTRAINT "EMPLOYEE_SKILLS_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_SKILLS" ADD CONSTRAINT "EMPLOYEE_SKILLS_Service_ID_fkey" FOREIGN KEY ("Service_ID") REFERENCES "SERVICES"("Service_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_SCHEDULES" ADD CONSTRAINT "EMPLOYEE_SCHEDULES_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUSTOMER_PACKAGES" ADD CONSTRAINT "CUSTOMER_PACKAGES_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUSTOMER_PACKAGES" ADD CONSTRAINT "CUSTOMER_PACKAGES_Package_ID_fkey" FOREIGN KEY ("Package_ID") REFERENCES "PACKAGES"("Package_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVOICES" ADD CONSTRAINT "INVOICES_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKINGS" ADD CONSTRAINT "BOOKINGS_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKINGS" ADD CONSTRAINT "BOOKINGS_Invoice_ID_fkey" FOREIGN KEY ("Invoice_ID") REFERENCES "INVOICES"("Invoice_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_DETAILS" ADD CONSTRAINT "BOOKING_DETAILS_Booking_ID_fkey" FOREIGN KEY ("Booking_ID") REFERENCES "BOOKINGS"("Booking_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_DETAILS" ADD CONSTRAINT "BOOKING_DETAILS_Service_ID_fkey" FOREIGN KEY ("Service_ID") REFERENCES "SERVICES"("Service_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_DETAILS" ADD CONSTRAINT "BOOKING_DETAILS_Cust_Pkg_ID_fkey" FOREIGN KEY ("Cust_Pkg_ID") REFERENCES "CUSTOMER_PACKAGES"("Cust_Pkg_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_EMPLOYEES" ADD CONSTRAINT "BOOKING_EMPLOYEES_Booking_Detail_ID_fkey" FOREIGN KEY ("Booking_Detail_ID") REFERENCES "BOOKING_DETAILS"("Booking_Detail_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_EMPLOYEES" ADD CONSTRAINT "BOOKING_EMPLOYEES_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUSTOMER_PROGRESS" ADD CONSTRAINT "CUSTOMER_PROGRESS_Booking_Detail_ID_fkey" FOREIGN KEY ("Booking_Detail_ID") REFERENCES "BOOKING_DETAILS"("Booking_Detail_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_Invoice_ID_fkey" FOREIGN KEY ("Invoice_ID") REFERENCES "INVOICES"("Invoice_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_Order_ID_fkey" FOREIGN KEY ("Order_ID") REFERENCES "ORDERS"("Order_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_Product_ID_fkey" FOREIGN KEY ("Product_ID") REFERENCES "PRODUCTS"("Product_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
