/*
  Warnings:

  - The primary key for the `BOOKINGS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `BOOKING_DETAILS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `BOOKING_EMPLOYEES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `CUSTOMER_PACKAGES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `CUSTOMER_PROGRESS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `EMPLOYEE_SCHEDULES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `EMPLOYEE_SKILLS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `INVOICES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `ORDERS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `ORDER_DETAILS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `PACKAGES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `PRODUCTS` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `ROLES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `SERVICES` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `USERS` table will be changed. If it partially fails, the table could be left without primary key constraint.

*/
-- DropForeignKey
ALTER TABLE "BOOKINGS" DROP CONSTRAINT "BOOKINGS_Customer_ID_fkey";

-- DropForeignKey
ALTER TABLE "BOOKINGS" DROP CONSTRAINT "BOOKINGS_Invoice_ID_fkey";

-- DropForeignKey
ALTER TABLE "BOOKING_DETAILS" DROP CONSTRAINT "BOOKING_DETAILS_Booking_ID_fkey";

-- DropForeignKey
ALTER TABLE "BOOKING_DETAILS" DROP CONSTRAINT "BOOKING_DETAILS_Cust_Pkg_ID_fkey";

-- DropForeignKey
ALTER TABLE "BOOKING_DETAILS" DROP CONSTRAINT "BOOKING_DETAILS_Service_ID_fkey";

-- DropForeignKey
ALTER TABLE "BOOKING_EMPLOYEES" DROP CONSTRAINT "BOOKING_EMPLOYEES_Booking_Detail_ID_fkey";

-- DropForeignKey
ALTER TABLE "BOOKING_EMPLOYEES" DROP CONSTRAINT "BOOKING_EMPLOYEES_Employee_ID_fkey";

-- DropForeignKey
ALTER TABLE "CUSTOMER_PACKAGES" DROP CONSTRAINT "CUSTOMER_PACKAGES_Customer_ID_fkey";

-- DropForeignKey
ALTER TABLE "CUSTOMER_PACKAGES" DROP CONSTRAINT "CUSTOMER_PACKAGES_Package_ID_fkey";

-- DropForeignKey
ALTER TABLE "CUSTOMER_PROGRESS" DROP CONSTRAINT "CUSTOMER_PROGRESS_Booking_Detail_ID_fkey";

-- DropForeignKey
ALTER TABLE "EMPLOYEE_SCHEDULES" DROP CONSTRAINT "EMPLOYEE_SCHEDULES_Employee_ID_fkey";

-- DropForeignKey
ALTER TABLE "EMPLOYEE_SKILLS" DROP CONSTRAINT "EMPLOYEE_SKILLS_Employee_ID_fkey";

-- DropForeignKey
ALTER TABLE "EMPLOYEE_SKILLS" DROP CONSTRAINT "EMPLOYEE_SKILLS_Service_ID_fkey";

-- DropForeignKey
ALTER TABLE "INVOICES" DROP CONSTRAINT "INVOICES_Customer_ID_fkey";

-- DropForeignKey
ALTER TABLE "ORDERS" DROP CONSTRAINT "ORDERS_Customer_ID_fkey";

-- DropForeignKey
ALTER TABLE "ORDERS" DROP CONSTRAINT "ORDERS_Invoice_ID_fkey";

-- DropForeignKey
ALTER TABLE "ORDER_DETAILS" DROP CONSTRAINT "ORDER_DETAILS_Employee_ID_fkey";

-- DropForeignKey
ALTER TABLE "ORDER_DETAILS" DROP CONSTRAINT "ORDER_DETAILS_Order_ID_fkey";

-- DropForeignKey
ALTER TABLE "ORDER_DETAILS" DROP CONSTRAINT "ORDER_DETAILS_Product_ID_fkey";

-- DropForeignKey
ALTER TABLE "USERS" DROP CONSTRAINT "USERS_Role_ID_fkey";

-- AlterTable
ALTER TABLE "BOOKINGS" DROP CONSTRAINT "BOOKINGS_pkey",
ALTER COLUMN "Booking_ID" DROP DEFAULT,
ALTER COLUMN "Booking_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Customer_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Invoice_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "BOOKINGS_pkey" PRIMARY KEY ("Booking_ID");
DROP SEQUENCE "BOOKINGS_Booking_ID_seq";

-- AlterTable
ALTER TABLE "BOOKING_DETAILS" DROP CONSTRAINT "BOOKING_DETAILS_pkey",
ALTER COLUMN "Booking_Detail_ID" DROP DEFAULT,
ALTER COLUMN "Booking_Detail_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Booking_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Service_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Cust_Pkg_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "BOOKING_DETAILS_pkey" PRIMARY KEY ("Booking_Detail_ID");
DROP SEQUENCE "BOOKING_DETAILS_Booking_Detail_ID_seq";

-- AlterTable
ALTER TABLE "BOOKING_EMPLOYEES" DROP CONSTRAINT "BOOKING_EMPLOYEES_pkey",
ALTER COLUMN "BE_ID" DROP DEFAULT,
ALTER COLUMN "BE_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Booking_Detail_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Employee_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "BOOKING_EMPLOYEES_pkey" PRIMARY KEY ("BE_ID");
DROP SEQUENCE "BOOKING_EMPLOYEES_BE_ID_seq";

-- AlterTable
ALTER TABLE "CUSTOMER_PACKAGES" DROP CONSTRAINT "CUSTOMER_PACKAGES_pkey",
ALTER COLUMN "Cust_Pkg_ID" DROP DEFAULT,
ALTER COLUMN "Cust_Pkg_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Customer_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Package_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "CUSTOMER_PACKAGES_pkey" PRIMARY KEY ("Cust_Pkg_ID");
DROP SEQUENCE "CUSTOMER_PACKAGES_Cust_Pkg_ID_seq";

-- AlterTable
ALTER TABLE "CUSTOMER_PROGRESS" DROP CONSTRAINT "CUSTOMER_PROGRESS_pkey",
ALTER COLUMN "Progress_ID" DROP DEFAULT,
ALTER COLUMN "Progress_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Booking_Detail_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "CUSTOMER_PROGRESS_pkey" PRIMARY KEY ("Progress_ID");
DROP SEQUENCE "CUSTOMER_PROGRESS_Progress_ID_seq";

-- AlterTable
ALTER TABLE "EMPLOYEE_SCHEDULES" DROP CONSTRAINT "EMPLOYEE_SCHEDULES_pkey",
ALTER COLUMN "Schedule_ID" DROP DEFAULT,
ALTER COLUMN "Schedule_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Employee_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "EMPLOYEE_SCHEDULES_pkey" PRIMARY KEY ("Schedule_ID");
DROP SEQUENCE "EMPLOYEE_SCHEDULES_Schedule_ID_seq";

-- AlterTable
ALTER TABLE "EMPLOYEE_SKILLS" DROP CONSTRAINT "EMPLOYEE_SKILLS_pkey",
ALTER COLUMN "Skill_ID" DROP DEFAULT,
ALTER COLUMN "Skill_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Employee_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Service_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "EMPLOYEE_SKILLS_pkey" PRIMARY KEY ("Skill_ID");
DROP SEQUENCE "EMPLOYEE_SKILLS_Skill_ID_seq";

-- AlterTable
ALTER TABLE "INVOICES" DROP CONSTRAINT "INVOICES_pkey",
ALTER COLUMN "Invoice_ID" DROP DEFAULT,
ALTER COLUMN "Invoice_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Customer_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "INVOICES_pkey" PRIMARY KEY ("Invoice_ID");
DROP SEQUENCE "INVOICES_Invoice_ID_seq";

-- AlterTable
ALTER TABLE "ORDERS" DROP CONSTRAINT "ORDERS_pkey",
ALTER COLUMN "Order_ID" DROP DEFAULT,
ALTER COLUMN "Order_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Customer_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Invoice_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "ORDERS_pkey" PRIMARY KEY ("Order_ID");
DROP SEQUENCE "ORDERS_Order_ID_seq";

-- AlterTable
ALTER TABLE "ORDER_DETAILS" DROP CONSTRAINT "ORDER_DETAILS_pkey",
ALTER COLUMN "Order_Detail_ID" DROP DEFAULT,
ALTER COLUMN "Order_Detail_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Order_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Product_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Employee_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "ORDER_DETAILS_pkey" PRIMARY KEY ("Order_Detail_ID");
DROP SEQUENCE "ORDER_DETAILS_Order_Detail_ID_seq";

-- AlterTable
ALTER TABLE "PACKAGES" DROP CONSTRAINT "PACKAGES_pkey",
ALTER COLUMN "Package_ID" DROP DEFAULT,
ALTER COLUMN "Package_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "PACKAGES_pkey" PRIMARY KEY ("Package_ID");
DROP SEQUENCE "PACKAGES_Package_ID_seq";

-- AlterTable
ALTER TABLE "PRODUCTS" DROP CONSTRAINT "PRODUCTS_pkey",
ALTER COLUMN "Product_ID" DROP DEFAULT,
ALTER COLUMN "Product_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "PRODUCTS_pkey" PRIMARY KEY ("Product_ID");
DROP SEQUENCE "PRODUCTS_Product_ID_seq";

-- AlterTable
ALTER TABLE "ROLES" DROP CONSTRAINT "ROLES_pkey",
ALTER COLUMN "Role_ID" DROP DEFAULT,
ALTER COLUMN "Role_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "ROLES_pkey" PRIMARY KEY ("Role_ID");
DROP SEQUENCE "ROLES_Role_ID_seq";

-- AlterTable
ALTER TABLE "SERVICES" DROP CONSTRAINT "SERVICES_pkey",
ALTER COLUMN "Service_ID" DROP DEFAULT,
ALTER COLUMN "Service_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "SERVICES_pkey" PRIMARY KEY ("Service_ID");
DROP SEQUENCE "SERVICES_Service_ID_seq";

-- AlterTable
ALTER TABLE "USERS" DROP CONSTRAINT "USERS_pkey",
ALTER COLUMN "User_ID" DROP DEFAULT,
ALTER COLUMN "User_ID" SET DATA TYPE TEXT,
ALTER COLUMN "Role_ID" SET DATA TYPE TEXT,
ADD CONSTRAINT "USERS_pkey" PRIMARY KEY ("User_ID");
DROP SEQUENCE "USERS_User_ID_seq";

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_Role_ID_fkey" FOREIGN KEY ("Role_ID") REFERENCES "ROLES"("Role_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_SKILLS" ADD CONSTRAINT "EMPLOYEE_SKILLS_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_SKILLS" ADD CONSTRAINT "EMPLOYEE_SKILLS_Service_ID_fkey" FOREIGN KEY ("Service_ID") REFERENCES "SERVICES"("Service_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_SCHEDULES" ADD CONSTRAINT "EMPLOYEE_SCHEDULES_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUSTOMER_PACKAGES" ADD CONSTRAINT "CUSTOMER_PACKAGES_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUSTOMER_PACKAGES" ADD CONSTRAINT "CUSTOMER_PACKAGES_Package_ID_fkey" FOREIGN KEY ("Package_ID") REFERENCES "PACKAGES"("Package_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVOICES" ADD CONSTRAINT "INVOICES_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKINGS" ADD CONSTRAINT "BOOKINGS_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKINGS" ADD CONSTRAINT "BOOKINGS_Invoice_ID_fkey" FOREIGN KEY ("Invoice_ID") REFERENCES "INVOICES"("Invoice_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_DETAILS" ADD CONSTRAINT "BOOKING_DETAILS_Booking_ID_fkey" FOREIGN KEY ("Booking_ID") REFERENCES "BOOKINGS"("Booking_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_DETAILS" ADD CONSTRAINT "BOOKING_DETAILS_Service_ID_fkey" FOREIGN KEY ("Service_ID") REFERENCES "SERVICES"("Service_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_DETAILS" ADD CONSTRAINT "BOOKING_DETAILS_Cust_Pkg_ID_fkey" FOREIGN KEY ("Cust_Pkg_ID") REFERENCES "CUSTOMER_PACKAGES"("Cust_Pkg_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_EMPLOYEES" ADD CONSTRAINT "BOOKING_EMPLOYEES_Booking_Detail_ID_fkey" FOREIGN KEY ("Booking_Detail_ID") REFERENCES "BOOKING_DETAILS"("Booking_Detail_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BOOKING_EMPLOYEES" ADD CONSTRAINT "BOOKING_EMPLOYEES_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUSTOMER_PROGRESS" ADD CONSTRAINT "CUSTOMER_PROGRESS_Booking_Detail_ID_fkey" FOREIGN KEY ("Booking_Detail_ID") REFERENCES "BOOKING_DETAILS"("Booking_Detail_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_Customer_ID_fkey" FOREIGN KEY ("Customer_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_Invoice_ID_fkey" FOREIGN KEY ("Invoice_ID") REFERENCES "INVOICES"("Invoice_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_Order_ID_fkey" FOREIGN KEY ("Order_ID") REFERENCES "ORDERS"("Order_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_Product_ID_fkey" FOREIGN KEY ("Product_ID") REFERENCES "PRODUCTS"("Product_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_Employee_ID_fkey" FOREIGN KEY ("Employee_ID") REFERENCES "USERS"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
