name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Mỗi khi bạn push lên nhánh main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Generate Prisma Client
        run: yarn prisma generate
        
      - name: Build project
        run: yarn build